# Production compose file

services:
    app:
        image: ghcr.io/actuallylost/tveeter-app:latest
        networks:
            tveeter_nw:
                ipv4_address: 172.30.1.2
        env_file:
            - ./app/.env
        depends_on:
            - api
    api:
        image: ghcr.io/actuallylost/tveeter-api:latest
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        networks:
            tveeter_nw:
                ipv4_address: 172.30.1.3
        env_file:
            - ./api/.env
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres:alpine
        env_file: .env
        networks:
            tveeter_nw:
                ipv4_address: 172.30.1.4

networks:
    tveeter_nw:
        ipam:
            config:
                - subnet: 172.30.1.0/24
                - gateway: 172.30.1.1
