services:
    app:
        build: app
        ports:
            - "8080:8080"
    api:
        build: api
        depends_on:
            - db
        ports:
            - "3000:3000"
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
