FROM oven/bun:alpine

RUN apk add --no-cache bash
RUN apk add --no-cache --virtual .builds-deps build-base python3
WORKDIR /app

COPY package.json .
RUN bun add --global pnpm
RUN pnpm install
COPY . .
RUN pnpm build

CMD ["pnpm", "start"]