name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build Tveeter Web Docker Image
              run: docker build ../../web --file Dockerfile --tag tveeter-web:latest
            - name: Build Tveeter API Docker Image
              run: docker build ../../api --file Dockerfile --tag tveeter-api:latest
